version: '3'
services:
  usermicroservices:
    build: ./BackEnd/usermicroservices
    ports:
     - "8080:8080"
    volumes:
     - .:/code
  bookmicroservices:
    build: ./BackEnd/bookmicroservices
    ports:
      - "8081:8080"
    volumes:
     - .:/code
  reviewmicroservices:
    build: ./BackEnd/reviewmicroservices
    ports:
      - "8082:8080"
    volumes:
     - .:/code
  checkoutmicroservices:
    build: ./BackEnd/checkoutmicroservices
    ports:
      - "8083:8080"
    volumes:
     - .:/code
  frontend:
    build: ./FrontEnd/myfirstapp
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true
    command: npm start